

service: express-passport
package:
  exclude:
  - .**
  - .vscode/**

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true